export const CONSTRUCT_IDS = {
  FOUNDATION_STACK: "FoundationStack",
  APP_STACK: "AppStack",
  EXPLICIT_VPC: "ExplicitVpc",
  EXPLICIT_SUBNETS: "ExplicitSubnets",
  EXPLICIT_INTERNET_GATEWAY: "ExplicitInternetGateway",
  EXPLICIT_ROUTE_TABLES: "ExplicitRouteTables",
  EXPLICIT_SECURITY_GROUPS: "ExplicitSecurityGroups",
  EXPLICIT_S3: "ExplicitS3",
  EXPLICIT_CLOUDTRAIL: "ExplicitCloudTrail",
  EXPLICIT_ECS: "ExplicitEcs",
  EXPLICIT_CLUSTER: "ExplicitCluster",
  EXPLICIT_ECR: "ExplicitEcr",
  EXPLICIT_TASK_DEFINITION: "ExplicitTaskDefinition",
  EXPLICIT_ECS_SERVICE: "ExplicitEcsService",
  EXPLICIT_ELB: "ExplicitElb",
  EXPLICIT_NLB: "ExplicitNlb",
  EXPLICIT_TARGET_GROUP: "ExplicitTargetGroup",
  EXPLICIT_LISTENER: "ExplicitListener",
} as const;
