export const RESOURCE_IDS = {
  VPC: "Vpc",
  INTERNET_GATEWAY: "InternetGateway",
  INTERNET_GATEWAY_ATTACHMENT: "InternetGatewayAttachment",
  BUCKET: "Bucket",
  TRAIL: "Trail",
  CLUSTER: "Cluster",
  REPOSITORY: "Repository",
  SERVICE: "Service",
  NETWORK_LOAD_BALANCER: "NetworkLoadBalancer",
  LISTENER: "Listener",
  TASK_DEFINITION: "TaskDefinition",
  TARGET_GROUP: "TargetGroup",
  PUBLIC_SUBNET_A: "PublicSubnetA",
  PUBLIC_SUBNET_B: "PublicSubnetB",
  PRIVATE_SUBNET_A: "PrivateSubnetA",
  PRIVATE_SUBNET_B: "PrivateSubnetB",
  PUBLIC_ROUTE_TABLE: "PublicRouteTable",
  PRIVATE_ROUTE_TABLE: "PrivateRouteTable",
  PUBLIC_DEFAULT_ROUTE: "PublicDefaultRoute",
  PUBLIC_SUBNET_ASSOC_A: "PublicSubnetAssocA",
  PUBLIC_SUBNET_ASSOC_B: "PublicSubnetAssocB",
  PRIVATE_SUBNET_ASSOC_A: "PrivateSubnetAssocA",
  PRIVATE_SUBNET_ASSOC_B: "PrivateSubnetAssocB",
  PUBLIC_SECURITY_GROUP: "PublicSecurityGroup",
  APP_SECURITY_GROUP: "AppSecurityGroup",
} as const;
