services:
  localstack:
    image: localstack/localstack:3.5
    container_name: ans-c01-localstack
    ports:
      - "${EDGE_PORT:-4566}:4566"
    environment:
      - SERVICES=cloudformation,cloudtrail,ec2,ecr,ecs,elasticloadbalancing,s3,sts,iam
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - DEBUG=0
      - EAGER_SERVICE_LOADING=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init:/etc/localstack/init/ready.d
